name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    outputs:
      lambda_url: ${{ steps.get-lambda-url.outputs.lambda_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18'

      - name: Install Dependencies
        run: |
          yarn install
 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      
      - name: Get Lambda URL
        id: get-lambda-url
        run: |
          # Use AWS CLI to get the URL of your Lambda function
          lambda_url=$(aws lambda get-function-url-config --function-name CBFAllocator --query "FunctionUrl" --output text)
          touch ../../.env
          echo $lambda_url >> ../../.env
          echo "::set-output name=lambda_url::$lambda_url"

      - name: Build React App
        run: |
          set REACT_APP_BACKEND_URL=${{ needs.get-lambda-url.outputs.lambda_url }} && yarn build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.3.0
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: build/
          REACT_APP_BACKEND_URL: ${{ needs.get-lambda-url.outputs.lambda_url }}
          DEST_DIR: /
          CI: ""
