name: Deploy to S3

on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    outputs:
      lambda_url: ${{ steps.get-lambda-url.outputs.lambda_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18'

      - name: Install Dependencies
        run: |
          npm install


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      
      - name: Get Lambda URL
        id: get_lambda_url
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          if [[ $branch == main ]]; 
            then 
              env_name=""
          else 
            env_name="dev"
          fi
          echo "env_name=${env_name}" >> $GITHUB_OUTPUT
          # Use AWS CLI to get the URL of your Lambda function
          lambda_url=$(aws lambda get-function-url-config --function-name CBFAllocator${env_name} --query "FunctionUrl" --output text)
          echo REACT_APP_BACKEND_URL="${lambda_url::-1}" >> $GITHUB_WORKSPACE/.env
          cat $GITHUB_WORKSPACE/.env
          echo "::set-output name=lambda_url::$lambda_url"

      - name: Build React App
        run: |
          npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.3.0
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}${{ steps.get_lambda_url.outputs.env_name }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: build/
          DEST_DIR: /
